import type { CanonicalSubmission } from "@/lib/domain/types";

/**
 * Deterministic, hand-authored synthetic commercial-property submissions.
 *
 * These are designed to run through the real property appetite engine
 * (`lib/domain/appetite/lines/property.ts`) and land on specific statuses:
 * a healthy block of in-appetite deals, the exact-value boundary cases the
 * engine treats as `needs_investigation`, missing-field ("needs evidence")
 * cases, and clear `out_of_appetite` contradictions.
 *
 * Every value is hardcoded — no randomness, no Date.now — so the resulting
 * queue is byte-stable across runs. A later task merges these into the
 * "Extended" dataset and flags them `synthetic: true`; this module only
 * authors the data.
 */
const SUBMISSIONS: CanonicalSubmission[] = [
  // 1–4: In-appetite, every factor at target.
  {
    id: "SUB-SYN-0001",
    accountName: "Pacific Ridge Logistics Center",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-01-01",
    expirationDate: "2027-01-01",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },
  {
    id: "SUB-SYN-0002",
    accountName: "Gulfstream Cold Storage",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "FL",
    effectiveDate: "2026-02-15",
    expirationDate: "2027-02-15",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },
  {
    id: "SUB-SYN-0003",
    accountName: "Front Range Distribution Hub",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CO",
    effectiveDate: "2026-03-01",
    expirationDate: "2027-03-01",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },
  {
    id: "SUB-SYN-0004",
    accountName: "Buckeye Manufacturing Campus",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "OH",
    effectiveDate: "2026-04-01",
    expirationDate: "2027-04-01",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },

  // 5–6: In-appetite on the acceptable edges (acceptable state, near-limit TIV,
  // acceptable-but-not-target premium, post-1990 build, construction just over half).
  {
    id: "SUB-SYN-0005",
    accountName: "Carolina Piedmont Textiles",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "NC",
    effectiveDate: "2026-05-01",
    expirationDate: "2027-05-01",
    tiv: 140_000_000,
    totalPremium: 60_000,
    buildingYear: 1995,
    approvedConstructionPercentage: 0.6,
    constructionDescription: "Masonry Non-Combustible, Frame",
    fiveYearLossValue: 90_000,
  },
  {
    id: "SUB-SYN-0006",
    accountName: "Old Dominion Warehouse Group",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "VA",
    effectiveDate: "2026-06-01",
    expirationDate: "2027-06-01",
    tiv: 140_000_000,
    totalPremium: 60_000,
    buildingYear: 1995,
    approvedConstructionPercentage: 0.6,
    constructionDescription: "Masonry Non-Combustible, Frame",
    fiveYearLossValue: 90_000,
  },

  // 7: Boundary — building year exactly 1990 → needs_investigation.
  {
    id: "SUB-SYN-0007",
    accountName: "Keystone Commerce Park",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "PA",
    effectiveDate: "2026-07-01",
    expirationDate: "2027-07-01",
    tiv: 80_000_000,
    totalPremium: 85_000,
    buildingYear: 1990,
    approvedConstructionPercentage: 0.7,
    constructionDescription: "Masonry Non-Combustible, Joisted Masonry",
    fiveYearLossValue: 50_000,
  },

  // 8: Boundary — TIV exactly $150M is acceptable (not >150M) → in-appetite.
  {
    id: "SUB-SYN-0008",
    accountName: "Chesapeake Bay Industrial Estate",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "MD",
    effectiveDate: "2026-08-01",
    expirationDate: "2027-08-01",
    tiv: 150_000_000,
    totalPremium: 90_000,
    buildingYear: 2012,
    approvedConstructionPercentage: 0.9,
    constructionDescription: "Fire Resistive, Non-Combustible",
    fiveYearLossValue: 10_000,
  },

  // 9: Boundary — construction exactly 50/50 → needs_investigation.
  {
    id: "SUB-SYN-0009",
    accountName: "Golden State Mixed-Use Portfolio",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-09-01",
    expirationDate: "2027-09-01",
    tiv: 70_000_000,
    totalPremium: 80_000,
    buildingYear: 2011,
    approvedConstructionPercentage: 0.5,
    constructionDescription: "Masonry Non-Combustible, Frame (even split)",
    fiveYearLossValue: 20_000,
  },

  // 10: Boundary — five-year losses exactly $100K → needs_investigation.
  {
    id: "SUB-SYN-0010",
    accountName: "Sunshine Retail Holdings",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "FL",
    effectiveDate: "2026-10-01",
    expirationDate: "2027-10-01",
    tiv: 65_000_000,
    totalPremium: 82_000,
    buildingYear: 2013,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 100_000,
  },

  // 11: Needs evidence — missing premium.
  {
    id: "SUB-SYN-0011",
    accountName: "Redwood Tech Fulfillment",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-11-01",
    expirationDate: "2027-11-01",
    tiv: 75_000_000,
    buildingYear: 2014,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },

  // 12: Needs evidence — missing five-year losses.
  {
    id: "SUB-SYN-0012",
    accountName: "Great Lakes Assembly Works",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "OH",
    effectiveDate: "2026-12-01",
    expirationDate: "2027-12-01",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2014,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
  },

  // 13: Needs evidence — missing building year.
  {
    id: "SUB-SYN-0013",
    accountName: "Mile High Storage Solutions",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CO",
    effectiveDate: "2026-01-15",
    expirationDate: "2027-01-15",
    tiv: 75_000_000,
    totalPremium: 88_000,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },

  // 14: Contradiction — pre-1990 building → out_of_appetite.
  {
    id: "SUB-SYN-0014",
    accountName: "Bayfront Heritage Mills",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-02-01",
    expirationDate: "2027-02-01",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 1965,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },

  // 15: Contradiction — premium far above the $175K limit → out_of_appetite.
  {
    id: "SUB-SYN-0015",
    accountName: "Silicon Valley Data Halls",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-03-15",
    expirationDate: "2027-03-15",
    tiv: 75_000_000,
    totalPremium: 400_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },

  // 16: Contradiction — risk state outside the listed appetite → out_of_appetite.
  {
    id: "SUB-SYN-0016",
    accountName: "Lone Star Freight Terminals",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "TX",
    effectiveDate: "2026-04-15",
    expirationDate: "2027-04-15",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },

  // 17–19: Out of appetite — renewal business is not acceptable.
  {
    id: "SUB-SYN-0017",
    accountName: "Coastline Property Trust (Renewal)",
    submissionType: "renewal",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-05-15",
    expirationDate: "2027-05-15",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },
  {
    id: "SUB-SYN-0018",
    accountName: "Everglade Commercial Renewals",
    submissionType: "renewal",
    lineOfBusiness: "property",
    primaryRiskState: "FL",
    effectiveDate: "2026-06-15",
    expirationDate: "2027-06-15",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },
  {
    id: "SUB-SYN-0019",
    accountName: "Rust Belt Renewal Partners",
    submissionType: "renewal",
    lineOfBusiness: "property",
    primaryRiskState: "OH",
    effectiveDate: "2026-07-15",
    expirationDate: "2027-07-15",
    tiv: 75_000_000,
    totalPremium: 88_000,
    buildingYear: 2015,
    approvedConstructionPercentage: 0.8,
    constructionDescription: "Masonry Non-Combustible, Non-Combustible",
    fiveYearLossValue: 40_000,
  },

  // 20–22: Multi-location in-appetite; construction just over half across the schedule.
  {
    id: "SUB-SYN-0020",
    accountName: "Anchor Portfolio — West Coast (12 buildings)",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-08-15",
    expirationDate: "2027-08-15",
    tiv: 90_000_000,
    totalPremium: 95_000,
    buildingYear: 2016,
    approvedConstructionPercentage: 0.55,
    constructionDescription: "12-building schedule: Masonry Non-Combustible and Frame mix",
    fiveYearLossValue: 30_000,
  },
  {
    id: "SUB-SYN-0021",
    accountName: "Anchor Portfolio — Southwest (9 buildings)",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-09-15",
    expirationDate: "2027-09-15",
    tiv: 90_000_000,
    totalPremium: 95_000,
    buildingYear: 2016,
    approvedConstructionPercentage: 0.55,
    constructionDescription: "9-building schedule: Masonry Non-Combustible and Frame mix",
    fiveYearLossValue: 30_000,
  },
  {
    id: "SUB-SYN-0022",
    accountName: "Anchor Portfolio — Central Valley (15 buildings)",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-10-15",
    expirationDate: "2027-10-15",
    tiv: 90_000_000,
    totalPremium: 95_000,
    buildingYear: 2016,
    approvedConstructionPercentage: 0.55,
    constructionDescription: "15-building schedule: Masonry Non-Combustible and Frame mix",
    fiveYearLossValue: 30_000,
  },

  // 23–24: High-hazard target geographies but fully in-appetite on the fundamentals.
  {
    id: "SUB-SYN-0023",
    accountName: "Wildfire Ridge Business Park",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "CA",
    effectiveDate: "2026-11-15",
    expirationDate: "2027-11-15",
    tiv: 85_000_000,
    totalPremium: 92_000,
    buildingYear: 2014,
    approvedConstructionPercentage: 0.85,
    constructionDescription: "Fire Resistive, Non-Combustible",
    fiveYearLossValue: 25_000,
  },
  {
    id: "SUB-SYN-0024",
    accountName: "Hurricane Coast Logistics",
    submissionType: "new",
    lineOfBusiness: "property",
    primaryRiskState: "FL",
    effectiveDate: "2026-12-15",
    expirationDate: "2027-12-15",
    tiv: 85_000_000,
    totalPremium: 92_000,
    buildingYear: 2014,
    approvedConstructionPercentage: 0.85,
    constructionDescription: "Fire Resistive, Non-Combustible",
    fiveYearLossValue: 25_000,
  },
];

/** Fresh copies of the deterministic synthetic property submissions. */
export function syntheticPropertySubmissions(): CanonicalSubmission[] {
  return SUBMISSIONS.map((s) => ({ ...s }));
}
